# Generated by Django 4.0.6 on 2022-08-29 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountBookRecord',
            new_name='RestaurantRecord',
        ),
    ]
