# Generated by Django 4.0.6 on 2022-08-29 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_accountbookrecord_restaurantrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantrecord',
            old_name='data',
            new_name='date',
        ),
    ]
